# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 23:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Survey_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('when_created', models.DateTimeField(auto_now_add=True)),
                ('multiple_answer', models.BooleanField(default=False)),
                ('end_date', models.DateTimeField()),
                ('card_color', models.CharField(choices=[('#D98880', 'red'), ('#F1948A', 'pink'), ('#C39BD3', 'purple'), ('#BB8FCE', 'violet'), ('#7FB3D5', 'blue'), ('#85C1E9', 'light-blue'), ('#76D7C4', 'light-blue-green'), ('#73C6B6', 'blue-green'), ('#7DCEA0', 'green'), ('#82E0AA', 'light-green'), ('#F7DC6F', 'yellow'), ('#F8C471', 'yellow-orange'), ('#F0B27A', 'light-orange'), ('#E59866', 'orange')], default='#D98880', max_length=7)),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Surveys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='survey_choices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Choices', to='Polls.Survey_Questions'),
        ),
        migrations.AddField(
            model_name='responses',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responses', to='Polls.Survey_Choices'),
        ),
        migrations.AddField(
            model_name='responses',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responses', to='Polls.Survey_Questions'),
        ),
        migrations.AddField(
            model_name='responses',
            name='user_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Responses', to=settings.AUTH_USER_MODEL),
        ),
    ]
