# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0003_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey_questions',
            name='multiple_answer',
            field=models.BooleanField(default=False),
        ),
    ]
