# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 03:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0004_auto_20170519_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey_questions',
            name='no_of_respondents',
        ),
    ]
