# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0005_remove_survey_questions_no_of_respondents'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey_questions',
            name='card_color',
            field=models.CharField(default='#D98880', max_length=7),
        ),
    ]
